plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ipeproing.countdowntv'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ipeproing.countdowntv'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
    buildTypes {
        release {
            // Installable release-mode build using the CI test certificate.
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
